### ISSUE TITLE
elastic4s release v7.17.3 uses elasticsearch 8.3.2

### ISSUE THREAD

**Issue by via119** [sksamuel/elastic4s#2710]
Hello,

it seems that some commits for the different elastic4s versions got mixed up.
7.17.3 was released from the master branch and it contains 8.3.2 elasticsearch and client for testing instead of 7.17.3.

The [PR](https://github.com/sksamuel/elastic4s/commit/f35797248b7bd8e011e6052173a10b6d92278791) that I made for [this](https://github.com/sksamuel/elastic4s/issues/2681) issue is not available in 7.17.3.

If it helps, I can open a new PR rebased to v7.17.2 tag so you can release a new 7.17.x version from that.

**Comment by sksamuel** [comment]
Yes that would help ! thank you.

**Comment by via119** [comment]
Taking a second look at it: 
It seems that the mentioned fix was successfully merged into the branch origin/release/7.12.x (f35797248) which is 1 commit ahead of the tag v7.17.2.
However, the v7.17.3 tag is not on this commit, but on ac091c93f which was a README update on the master branch.

Can you release a new 7.17.x version from the origin/release/7.12.x branch? Thank you!

**Comment by sksamuel** [comment]
I released 7.17.4 but forgot to come back and mention it.

**Comment by PeterHajdu** [comment]
Hi Sam!

Just noticed that v7.17.4 tag was added again to the top of the master branch. (commit: 4211ff45b)
Unfortunately we need a release from an older branch so that we can use it with elasticsearch 7.17.1.
Can you please make a release from the branch "release/7.12.x" (commit: f35797248)?

Thanks in advance.

**Comment by OriHoch** [comment]
hi, this issue still exists, it seems both 7.17.3 and 7.17.4 use elasticsearch 8
