### ISSUE TITLE
ElasticSearch 5 support

### ISSUE THREAD

**Issue by carnalim** [sksamuel/elastic4s#634]
I know ES is only in Alpha 5 as of time of writing this but, curious if there is already an initiative underway to make elastic4s work with ES5?

**Comment by sksamuel** [comment]
Yes I have started it locally.

**Comment by fernandomora** [comment]
ES 5.0.0 final has bee released https://www.elastic.co/blog/elastic-stack-5-0-0-released

**Comment by sksamuel** [comment]
I'm a couple of days behind.

**Comment by TrustNoOne** [comment]
Great job as always 👍  Just a quick question: do all the issues in the 5.0 milestone need to be resolved for the first 5.0-compatible version to be released?

**Comment by sksamuel** [comment]
No I'm in need of a build asap to unblock my team at work so am trying to
get one out. Was meant to be last week but they've changed so much stuff.

**Comment by sksamuel** [comment]
Getting there.

Total 308, Failed 88, Errors 3, Passed 217, Ignored 6

**Comment by mariussoutier** [comment]
Can we also increase the version to 5? Would make things both more consistent and transprent.

**Comment by sksamuel** [comment]
My thinking is this - when I had the version tied to elasticsearch itself, I was unable to add new features and bump the version without waiting for the next es version too.

For example, if I have 5.0.0 and we add a new feature, we have to wait for 5.1.0 to be released, as 5.0.1 should be a bug only fix.

**Comment by mariussoutier** [comment]
Ok good point. One alternative would be to make the first two digits equal ES, and use two additional for features and bug fixes. But maybe that's too confusing :)

**Comment by sksamuel** [comment]
I've thought about this a bit more and I am just going to call it 5.0.0.

**Comment by sksamuel** [comment]
5.0.0-ALPHA1 is on maven central. What's left is fixing aggregations to work with v5 but if you don't use aggregations then this release might be ok for you.

**Comment by TrustNoOne** [comment]
brilliant, is aggregation support just broken or missing at all? If it's there but it doesn't work I'll start migrating the non-aggregation code right away.

**Comment by sksamuel** [comment]
In Alpha2 it's there but I haven't migrated the rest of the tests so can't
confirm it works 100%.

Highlighting is missing as that has changed, that will be added tonight.

And inner hits is missing as that has changed in ES5 too.

**Comment by sksamuel** [comment]
Let me know how you get on @TrustNoOne

**Comment by TrustNoOne** [comment]
I started updating the code - a lot of the api is now reflection-based, is that intended or just temporary? 

I'll let you know as soon as I manage to run everything. I have an embedded local node for testing, I have to make that work as well.

**Comment by sksamuel** [comment]
I can't get scripting to work in embedded mode either - apparently its just _included_ in es but my debugging showed no script languages added. I'd use my LocalNode rather than try to write your own as I spent ages on it.

Thanks for the bug / missing reports, keep them coming, I'll fix all the fixable ones tonight.

**Comment by sksamuel** [comment]
I've just finished upgrading my project at Deutsche Bank and it was a lot less painful than I expected.

**Comment by TrustNoOne** [comment]
The only thing I haven't been able to port is a nested aggregation.
Unit tests are passing. I need an embedded instance with scripting for my integration tests, I'll run them against an external instance for the time being. 
It would be useful to have the list of plugins to load in a `LocalNode` constructor.

I'm now struggling with my integration tests, I'm getting  ` org.elasticsearch.index.query.QueryShardException: No mapping found for [_score] in order to sort on (FieldSortBuilder.java:266)`, I'm trying to understad why it wouldn't let me sort by score

**Comment by sksamuel** [comment]
You could create a LocalNode like new LocalNode(LocalNode.requiredSettings(...), plugins) but I'll update the companion methods to help. If you can figure out how to run scripts in an embedded instance please let me know!

**Comment by TrustNoOne** [comment]
All green running against an external instance! 

To make everything work I wrapped ElasticDsl in an "extended version" and added the following:
- extension method `field` for `RangeAggregationDefinition` 
- `implicit def toIndexAndType(indexAndType: (String, String)): IndexAndType`
- wrappers to avoid reflection warnings on `createTemplate` and `dynamicTemplate`
- extension method `created` to `UpdateResponse`

Other things that are missing:
- UpdateDefinition.doc(string) method
- date histogram dsl for interval/extendedBounds (also I'm using java8 dates and the api now takes joda timezones, but I suppose that's by design)
- `field type KeywordTyped` in dynamicTemplates to specify the default string mapping. I replaced it with `keywordField("")`, but maybe I should do it differently?

I'll remove everything as soon as it's fixed

Things I couldn't get to work (blocking for my upgrade, once I have this I'll be able to run a more comprehensive set of end-to-end tests):
- nested aggregation

Other problems I still have, unrelated to elastic4s (I guess): 
- logging - I have an exception when adding log4j2Slf4jAdapter to the classpath
- embedded scripting - lang-painless/groovy is not on maven central. I'll deploy it on our local artifactory and add it to the loaded plugins to see if it works. I can't use `LocalNode` because the list of plugins is hardcoded.

**Comment by sksamuel** [comment]
Painless code is here
https://github.com/elastic/elasticsearch/tree/master/modules/lang-painless
But I can't see it on central.

I can't figure out how they depend on it in the build or package it up for use in the binary.
https://github.com/elastic/elasticsearch/blob/master/build.gradle

**Comment by sksamuel** [comment]
UpdateDefinition.doc(string) method <-- are you wanting to pass in source json manually ?

**Comment by TrustNoOne** [comment]
Ok, I made it all work, this is the temporary wrapper class to ElasticDsl with everything I added: https://gist.github.com/TrustNoOne/677e0b37497e918bde712da1ef717a7e

Now I have to fix logging and try to load embedded scripting plugins.

**Comment by sksamuel** [comment]
I've released ALPHA3. I will release 5.0.0 final tomorrow night unless anything major comes up.

**Comment by TrustNoOne** [comment]
Trying it now. last few minor things still missing, not fundamental:
- RichAggregations: helper method for `filters` and `range` aggr (currently using getAs for those)
- RichAggregations: helper methods are leaking `InternalXyz` classes, I guess these classes are not supposed to be used directly?
- (String, String) => IndexAndType implicit conversion. (though I changed my code to use two parameters instead of tuples so I don't need it anymore)
- (String, String) => ExtendedBounds implicit conversion. I added it myself for the time being


Everything is looking good :+1:, I'll start working on getting embedded scripting working now. I'll let you know if I succeed.

Thanks for the quick support :)

On a side note: I do bulk indexing, throughput decreased by ~5x with es 5.0 (same mapping apart from `keyword` used wherever I had `string not analyzed`), I can't understand why. It's not the library anyway, it's es hogging the cpu, if you ever noticed something similar please let me know :)

**Comment by sksamuel** [comment]
Try the new bulk processor.

**Comment by sksamuel** [comment]
As for leaking `Interalxxx` classes, there are things like `MultiBucketsAggregation`, I'll check to see if that defines all the methods we need. If we can get scripting support in embedded then we're done. I might have to bundle painless with the embedded node.

**Comment by TrustNoOne** [comment]
The embedded instance started working (apparently) after adding the following dependencies:

      "com.sksamuel.elastic4s"     %% "elastic4s-embedded" % "5.0.0-ALPHA3"
      "org.elasticsearch.module" % "lang-painless" % "5.0.0" (not found on central)
      "org.antlr" % "antlr4-runtime" % "4.5.1" 
      "org.ow2.asm" % "asm" % "5.1"

I ran it like this:
```scala
    val settings = Settings.builder()
      .put("cluster.name", "test-cluster")
      .put("path.home", EmbeddedInstanceTmpDir)
      .put("path.repo", s"$EmbeddedInstanceTmpDir/repo")
      .put("path.data", s"$EmbeddedInstanceTmpDir/data")
      .put("script.inline", "true")
      .put("script.stored", "true")
      .put("transport.type", "local")
      .put("discovery.type", "local")
      .put("http.type", "netty3")
      .build()

    val plugins = List(classOf[Netty3Plugin], classOf[PainlessPlugin])

    new LocalNode(settings, plugins).elastic4sclient(shutdownNodeOnClose = true)
```

**Comment by carnalim** [comment]
I am getting the following trying to connect to a remote source (using RC1):
`<console>:70: error: value remote is not a member of object com.sksamuel.elastic4s.ElasticClient`

I am also seeing this:

```
val uri = ElasticsearchClientUri(elasticAddress)
java.lang.NoClassDefFoundError: com/sksamuel/exts/StringOption$
  at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticClient.scala:124)
  ... 68 elided
```

**Comment by sksamuel** [comment]
`remote` is not a method on ElasticClient anymore, it's `transport` now. It's like the project hasn't been recompiled properly after the dep update.

**Comment by carnalim** [comment]
I'm playing around in the spark shell and here is what I am doing (IP address taken out for obvious reasons):
```
scala> val elasticAddress = "elasticsearch://" + getEnvirometalParameter("streaming_pipeline", "elastic_address")(0)._1
elasticAddress: String = elasticsearch://xxxxxxx:9002

scala> val uri = ElasticsearchClientUri(elasticAddress)
java.lang.NoClassDefFoundError: com/sksamuel/exts/StringOption$
  at com.sksamuel.elastic4s.ElasticsearchClientUri$.apply(ElasticClient.scala:124)
  ... 70 elided

scala> val client = ElasticClient.transport("elasticsearch://xxxxxxx:9002")
java.lang.NoClassDefFoundError: com/sksamuel/exts/Logging
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 70 elided
Caused by: java.lang.ClassNotFoundException: com.sksamuel.exts.Logging
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 82 more
```

**Comment by sksamuel** [comment]
You need to add com.skamuel.exts jar to spark. It's on maven central.

**Comment by carnalim** [comment]
Getting closer, this is also with the org.elasticsearch 5.0 jar imported as well: 

```
scala>   val client = ElasticClient.transport(uri)
warning: Class org.apache.logging.log4j.Logger not found - continuing with a stub.
warning: Class org.apache.logging.log4j.Logger not found - continuing with a stub.
16/11/09 14:07:39 WARN ElasticClient$: No cluster.name was specified in the settings for the client." +
        "This will still work if your cluster has the default name, but it is recommended you always set the cluster.name to avoid issues
java.lang.NoClassDefFoundError: org/elasticsearch/transport/client/PreBuiltTransportClient
  at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:97)
  at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:65)
  ... 72 elided
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.transport.client.PreBuiltTransportClient
  at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 74 more
```

**Comment by sksamuel** [comment]
You need the transport jar not the full jar. I'm on my mobile so don't have
links handy but check the deps for the elastic4s  core project.

**Comment by sksamuel** [comment]
@carnalim So you will need this jar in spark as well
http://search.maven.org/#artifactdetails%7Corg.elasticsearch.client%7Ctransport%7C5.0.0%7Cjar

**Comment by sksamuel** [comment]
5.0.0 Published.

**Comment by TrustNoOne** [comment]
good job, I've been using it for some days and no problems so far 👍

**Comment by michaelqiu94** [comment]
I am trying to create an ElasticClient through the elasticsearch client uri connection string and I got this error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/Logger
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:105)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:72)
	at org.elasticsearch.common.component.AbstractComponent.<init>(AbstractComponent.java:37)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:110)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:81)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:106)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:228)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:69)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:65)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:101)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:67)

Ideas?

**Comment by akashsuresh** [comment]
Even I have a similar issue as @michaelqiu94 


Exception in thread "ForkJoinPool-1-worker-5" java.lang.NoSuchMethodError: org.apache.logging.log4j.status.StatusLogger.debug(Ljava/lang/String;Ljava/lang/Object;)V
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:91)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:58)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:93)
	at org.elasticsearch.common.logging.ESLoggerFactory.getLogger(ESLoggerFactory.java:49)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:105)
	at org.elasticsearch.common.logging.Loggers.getLogger(Loggers.java:72)
	at org.elasticsearch.common.component.AbstractComponent.<init>(AbstractComponent.java:37)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:110)
	at org.elasticsearch.client.transport.TransportClient.newPluginService(TransportClient.java:81)
	at org.elasticsearch.client.transport.TransportClient.buildTemplate(TransportClient.java:106)
	at org.elasticsearch.client.transport.TransportClient.<init>(TransportClient.java:228)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:69)
	at org.elasticsearch.transport.client.PreBuiltTransportClient.<init>(PreBuiltTransportClient.java:65)
	at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:101)
	at models.daos.NewsDAOImpl.listnews(NewsDAOImpl.scala:124)
	at controllers.NewsController$$anonfun$viewjson$1.apply(NewsController.scala:71)
	at controllers.NewsController$$anonfun$viewjson$1.apply(NewsController.scala:53)
	at com.mohiva.play.silhouette.api.actions.SecuredActionBuilder$$anonfun$1.apply(SecuredAction.scala:209)
	at com.mohiva.play.silhouette.api.actions.SecuredActionBuilder$$anonfun$1.apply(SecuredAction.scala:209)
	at com.mohiva.play.silhouette.api.actions.SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1$$anonfun$apply$1.apply(SecuredAction.scala:90)
	at com.mohiva.play.silhouette.api.actions.SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1$$anonfun$apply$1.apply(SecuredAction.scala:90)
	at com.mohiva.play.silhouette.api.RequestHandlerBuilder$class.handleInitializedAuthenticator(RequestHandler.scala:169)
	at com.mohiva.play.silhouette.api.RequestHandlerBuilder$class.handleBlock(RequestHandler.scala:119)
	at com.mohiva.play.silhouette.api.actions.SecuredRequestHandlerBuilder.handleBlock(SecuredAction.scala:52)
	at com.mohiva.play.silhouette.api.actions.SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1.apply(SecuredAction.scala:90)
	at com.mohiva.play.silhouette.api.actions.SecuredRequestHandlerBuilder$$anonfun$invokeBlock$1.apply(SecuredAction.scala:86)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by dmitry-avershin** [comment]
Hi, I'm getting the same issue with a "Class org.apache.logging.log4j.Logger not found - continuing with a stub." I have a log4j 1.2.17 library included in my project and using elastic4s 5.4.10 version. Any ideas what can be wrong here? Feels like some implementations are missing.

**Comment by dmitry-avershin** [comment]
In case you have some problems with missing org.apache.logging.Logger class, add
"org.apache.logging.log4j" % "log4j-core" % "2.8.2",
"org.apache.logging.log4j" % "log4j-api" % "2.8.2".

Starting from ES 5 they are required to be added separately.
